### ISSUE TITLE
Broken link in documentation

### ISSUE THREAD

**Issue by gauravpatil1** [mindsdb/mindsdb-docs#129]
Broken link on [mindsdb-docs/mindsdb-docs/docs/Installing.md](https://github.com/mindsdb/mindsdb-docs/blob/master/mindsdb-docs/docs/Installing.md)

Broken link - https://raw.githubusercontent.com/mindsdb/mindsdb/stable/distributions/docker/build-docker.sh

**Comment by ZoranPandovski** [comment]
Thanks for reporting this @gauravpatil1. I just removed that script since people can pull/run docker images with 2 commands. If you found any other issues feel free to open a new issue or contribute.
