### ISSUE TITLE
Add warning about MKL issue when using Docker

### ISSUE THREAD

**Issue by ZoranPandovski** [mindsdb/mindsdb-docs#145]
Using Docker sometimes the user may experience issues related to mkl and threading. We need to add info that it could be resolved by adding env var or starting Docker with

```
docker run --env MKL_SERVICE_FORCE_INTEL=1 -it -p 47334:47334 mindsdb/mindsdb
```

**Comment by dfrances1** [comment]
Updated.

**Comment by dfrances1** [comment]
Update complete.
