### ISSUE TITLE
Remove 'python 3.6', add 'update pip'

### ISSUE THREAD

**Issue by StpMax** [mindsdb/mindsdb-docs#186]
We need remove from doc mentions of python 3.6.
We need add to do 'update pip if version less than 19.0'

**Comment by Sumanth077** [comment]
Hi @StpMax is this issue Still Open?

**Comment by ZoranPandovski** [comment]
Hey @Sumanth077 we have migrated docs in https://github.com/mindsdb/mindsdb repo. Please check the issues there :raised_hands:
