### ISSUE TITLE
FAQ Section in Docs

### ISSUE THREAD

**Issue by AdamMCarrigan** [mindsdb/mindsdb-docs#207]
Add a FAQ sections to docs that we can continually add to. Questions written in plain english like "How can I see the model status" "How can I select which model framework I want to use?" etc. An exmaple is AWS https://aws.amazon.com/s3/faqs/

**Comment by martyna-mindsdb** [comment]
Created FAQs section: https://github.com/mindsdb/mindsdb/pull/6281
