### ISSUE TITLE
'Upload custom model' (BYOM in MindsDB) lacks documentation

### ISSUE THREAD

**Issue by Dav1dF** [mindsdb/mindsdb-docs#211]
# Context
We shipped the capability to upload Python files directly to MindsDB
This feature is available in open-source, AWS Marketplace and Minds Pro versions of MindsDB – but not on Cloud. The CTA (button) and upload page can be previewed on Cloud https://cloud.mindsdb.com/byom to offer the opportunity to discover this feature

# Current State
`Read our docs` redirects to https://docs.mindsdb.com/sql/create/databases which is confusing. This should at the very least redirect to a docs WIP page

![Screenshot 2023-04-04 at 17 27 55](https://user-images.githubusercontent.com/83925592/229858299-d4dd4b55-aec9-421c-b085-da87871216ae.png)

# Desired State
A docs page explaining the value of this feature and complimented by a walkthrough guide

**Comment by Dav1dF** [comment]
Dependency https://github.com/mindsdb/mindsdb-frontend/issues/1226

**Comment by martyna-mindsdb** [comment]
@Dav1dF 
I cannot access this issue:
![image](https://user-images.githubusercontent.com/109554435/232460234-5deb8cd0-6739-4560-bd9e-ef8451c34bc3.png)
