### ISSUE TITLE
Create docs page for Nixtla's TimeGPT

### ISSUE THREAD

**Issue by Dav1dF** [mindsdb/mindsdb-docs#220]
https://github.com/mindsdb/mindsdb/tree/staging/mindsdb/integrations/handlers/timegpt_handler

Refer to @paxcema for questions and guidance

**Comment by Dav1dF** [comment]
@martyna-mindsdb pls let @Hazemmahdyx when the link is ready

**Comment by paxcema** [comment]
Just FYI @martyna-mindsdb will be OOO for a while, we may want to reassign this given the time constraints for the launch on Monday.

**Comment by paxcema** [comment]
Right now current state of the handler is well reflected by the `README.md` tutorial, [here](https://github.com/mindsdb/mindsdb/tree/staging/mindsdb/integrations/handlers/timegpt_handler), plus the already live Learning Hub example.

This week I'll be working on a new anomaly detection mode that will leverage TimeGPT, but it is not built yet, so I suggest spinning up a basic version of the doc page based on the above.

For reference, here are Nixtla's [docs](https://docs.nixtla.io/docs/quickstart), very high quality too.
