### ISSUE TITLE
LLM 1.1 Create a new app or select an existing app

### ISSUE THREAD

**Issue by Dav1dF** [mindsdb/mindsdb-docs#223]
## Current
<img width="400" alt="Screenshot 2023-09-04 at 16 14 39" src="https://github.com/mindsdb/mindsdb-docs/assets/83925592/9548d381-fc04-4918-a448-22bd9ac4ad32">

## Expected

Create a new app or select an existing app.
Highlight the fact that the steps are based on creating From Scratch. If user wants to From an app manifest they should check [Slack’s docs](https://api.slack.com/reference/manifests)

https://www.loom.com/share/6a8b6e8e1bb040cd93bb37fadb5e59fb?sid=64008dc1-d248-40cf-8947-63139d44be99

**Comment by martyna-mindsdb** [comment]
@Dav1dF 
Here are the updates:
![image](https://github.com/mindsdb/mindsdb-docs/assets/109554435/d614a67f-18a1-4937-aecf-2327006e8853)
