### ISSUE TITLE
Unrecognized theme

### ISSUE THREAD

**Issue by mcroni** [mindsdb/mindsdb-docs#26]
`Config value: 'theme'. Error: Unrecognised theme name: 'material'. The available installed themes are: mkdocs, readthedocs` . Seems the installation package for material is needed

**Comment by ZoranPandovski** [comment]
@mcroni Did you try to start the docs locally? If so, you need to install material `pip install mkdocs-material`

**Comment by mcroni** [comment]
@ZoranPandovski i'm making some PRs, so it should be fine
