### ISSUE TITLE
Add Copy to Clipboard

### ISSUE THREAD

**Issue by ZoranPandovski** [mindsdb/mindsdb-docs#3]
We have a lot of code examples through the documentation so it would be good to implement `Copy to Clipboard` functionality.

**Comment by mcroni** [comment]
I think this issue should be closed. I've gone through the docs and the code examples all have the copy to clipboard functionality already implemented

**Comment by ZoranPandovski** [comment]
Yes, this functionality is implemented, thanks for pointing out @mcroni
