### ISSUE TITLE
Lists are not working inside <details> sections

### ISSUE THREAD

**Issue by ZoranPandovski** [mindsdb/mindsdb-docs#4]
The Unordered or ordered lists are not displayed correctly when used inside expandable sections. Check if this is an issue in material theme, or if there is additional Markdown syntax that we need to use?
![Screenshot from 2020-05-07 16-26-01](https://user-images.githubusercontent.com/7192539/81306471-ce9f1580-907f-11ea-88a3-dec09fc577a6.png)

**Comment by mcroni** [comment]
where did you try to implement this functionality

**Comment by ZoranPandovski** [comment]
This will be fixed by using the code formater ``` ``` @mcroni
