### ISSUE TITLE
Remove Connection page

### ISSUE THREAD

**Issue by ZoranPandovski** [mindsdb/mindsdb-docs#76]
The scout/Connection.md should be removed and also the Link in the [navigation](https://github.com/mindsdb/mindsdb-docs/blob/master/mindsdb-docs/mkdocs.yml#L64)

**Comment by RodolfoNei** [comment]
Hello! Can I please work on this issue?

**Comment by torrmal** [comment]
hi @RodolfoNei ofcourse!
