### ISSUE TITLE
Fix travis

### ISSUE THREAD

**Issue by ZoranPandovski** [mindsdb/mindsdb-docs#78]
Currently, Travis is failing because of the missing plugins. We need to include installation in the travis.yml https://travis-ci.com/github/mindsdb/mindsdb-docs/jobs/397735820#L271

**Comment by ry-v1** [comment]
@ZoranPandovski - Can I work on this

**Comment by ry-v1** [comment]
I added table-reader plugin to travis.yml. But getting another error. 
The table-reader plugin can read the files [Where the path is relative to the location of your project's mkdocs.yml file](https://pypi.org/project/mkdocs-table-reader-plugin/). 

For e.g. ChurnReduction.md has direct csv links which is causing the build to fail.
Can we add the add required csv files to this repo to fix the issue.

**Comment by ZoranPandovski** [comment]
Sure @ry-v1

**Comment by ZoranPandovski** [comment]
Can you make PR even if it is not fully functional, so I can help you? @ry-v1

**Comment by ry-v1** [comment]
Just submitted a PR #91
