### ISSUE TITLE
Trying to set up the doc server locally

### ISSUE THREAD

**Issue by chechu-arias** [mindsdb/mindsdb-docs#97]
So I forked the documentation repository and tried the step-guide in the README, but then I had a problem with table-reader:

```
ERROR   -  Config value: 'plugins'. Error: The "table-reader" plugin is not installed 

Aborted with 1 Configuration Errors!
```
Maybe that should be said in the README, or maybe it's just that I'm a beginner. Anyway, I then installed that plugin with pip and now I get this error:

```
INFO    -  Building documentation... 
WARNING -  Config value: 'plugins'. Warning: ('social', 'Unrecognised configuration name: social') 
INFO    -  Cleaning site directory 
INFO    -  The following pages exist in the docs directory, but are not included in the "nav" configuration:
  - index.md
  - features/ColumnMetrics.md
  - integrations/AwsSageMaker.md
  - integrations/CallSageMakerEndpoint.md
  - integrations/MindsDBSageContainer.md
  - integrations/SageMakerSDK.md
  - integrations/UseMindsDBinSage.md
  - scout/Databases.md 
ERROR   -  Error reading page 'tutorials/ChurnReduction.md': [table-reader-plugin]: File does not exist: ./https://raw.githubusercontent.com/mindsdb/mindsdb-examples/master/classics/churn/dataset/test.csv 

[table-reader-plugin]: File does not exist: ./https://raw.githubusercontent.com/mindsdb/mindsdb-examples/master/classics/churn/dataset/test.csv
```

I'm new and trying to learn in this open project so I'm sorry if it results to be a bad issue.

**Comment by ZoranPandovski** [comment]
Thank you @chechu-arias for reporting this one. I will need to update the docs. The problem you are getting is because of missing installation of table-reader plugin. You will need to do `pip install table-reader`

**Comment by chechu-arias** [comment]
I did say in the issue that after doing that I got the second error, so it wasn't fixed with the installation of table-reader.

**Comment by ZoranPandovski** [comment]
Yes, but you need specific version mkdocs-table-reader-plugin==0.3.0

**Comment by chechu-arias** [comment]
I installed the version that you said and it worked after I also installed mkdocs-material with pip. I hadn't used mkdocs before but with that I can now see the docs. Thank you for your help and maybe we could add that into a MD for installation purposes.

**Comment by ZoranPandovski** [comment]
Sure, thanks @chechu-arias
